---
- hosts: phoenix
  become: yes
  tasks:
  - name: change /etc/hosts
    lineinfile:
      path: '/etc/hosts'
      regexp: '.*pve.*' 
      line: '192.168.60.201   pve.example.com   pve' 
      backup: yes