---
- name: Update GRUB
  ansible.builtin.command: update-grub
  changed_when: false

- name: Proxmox Boot Tool Refresh
  ansible.builtin.command: proxmox-boot-tool refresh
  changed_when: false

- name: Restart chrony
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: true
  when: configure_ntp_servers_result.changed
  changed_when: configure_ntp_servers_result.changed

- name: Restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  notify:
    - Reset SSH connection

- name: Reset SSH connection
  ansible.builtin.meta: reset_connection

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: Restart pve-firewall
  ansible.builtin.service:
    name: pve-firewall
    state: restarted
  changed_when: false

- name: Reload ZFS Modules
  ansible.builtin.shell: |
    modprobe -r zfs && modprobe zfs
  changed_when: false

- name: Restart ksmtuned
  ansible.builtin.systemd:
    name: ksmtuned
    state: restarted

- name: Restart pveproxy service
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - pveproxy
    - pvestatd
    - pvedaemon
  when: web_show_temperatures | bool

- name: Restart Fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true