---
roles:
  - src: ironicbadger.docker_compose_generator
  - src: ironicbadger.proxmox_nag_removal

  - src: geerlingguy.docker
  - src: geerlingguy.dotfiles
  - src: geerlingguy.github-users

  - src: singleplatform-eng.users
  - src: sicruse.powerline-fonts
  - src: grog.package