services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      PUID: "{{ calibre_puid | default('1026') }}"
      PGID: "{{ calibre_pgid | default('100') }}"
      TZ: "{{ cerebro_timezone }}"
      DOCKER_MODS: "lscr.io/linuxserver/mods:universal-calibre"
    volumes:
      - "{{ cerebro_docker_root }}/calibre/config:/config"
      - "{{ cerebro_docker_root }}/calibre/library:/calibre-library"
      - "{{ cerebro_docker_root }}/calibre/ingest:/cwa-book-ingest"
    ports:
      - 8083:8083
    restart: unless-stopped
