---
# generic settings
main_username: boogeymarquez
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"
timezone: "America/Phoenix"
ntp_servers:
  - 2.pfsense.pool.ntp.org # Primary NTP server.
  - 1.pfsense.pool.ntp.org # Tertiary NTP server.

# singleplatform-eng.users
users:
  - username: "{{ main_username }}"
    name: "Anthony Marquez"
    groups: ['sudo','systemd-journal']
    uid: 1001
    shell: "/bin/zsh"
    ssh_key: 
    - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
groups_to_create:
  - name: "developers"
    gid: 10000

# ferrarimarco.bash-aliases
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' "}
  - { alias: "dstop", command: "docker stop `docker ps -aq`"}
  - { alias: "drm", command: "docker rm `docker ps -aq`"}
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml "}
  - { alias: "dcporph", command: "docker-compose -f ~/docker-compose.yml --remove-orphans "}
  - { alias: "dprune", command: "docker image prune"}
  - { alias: "dprunesys", command: "docker system prune --all"}
  - { alias: "bashreload", command: "source ~/.bashrc && echo Bash config reloaded;"}
  - { alias: "ctop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock http://quay.io/vektorlab/ctop "}
  - { alias: "sshclear", command: "rm ~/.ssh/multiplex/* -f && echo SSH connection cache cleared;"}
  - { alias: "sshlist", command: "echo Currently open ssh connections && echo && l ~/.ssh/multiplex/"}
  - { alias: "dfclean", command: "df -h -x tmpfs -x zfs -t fuse.mergerfs -t xfs -t ext4"}
  - { alias: "dfzfs", command: "df -h -x tmpfs -t fuse.mergerfs -t xfs -t ext4 -t zfs"}

# grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: git
  - name: fzf
  - name: htop
  - name: iftop
  - name: iotop
  - name: lm-sensors
  - name: mc
  - name: molly-guard
  - name: ncdu
  - name: net-tools
  - name: nfs-kernel-server
  - name: nmap
  - name: openssh-server
  - name: python3
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget

# weareinteractive.environment
environment_config: {
  "PUID": "{{ main_gid }}",
  "PGID": "{{ main_gid }}"
}

# geerlingguy.ntp
ntp_timezone: "America/Phoenix"

# geerlingguy.security
security_ssh_port: 22
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_autoupdate_enabled: true
security_fail2ban_enabled: true
security_sudoers_passwordless:
  - "{{ main_username }}"

# geerlingguy.docker
docker_compose_version: v2.17.2

# ironicbadger.docker_compose_generator
appdata_path: /opt/appdata
global_env_vars:
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: "/home/{{ main_username }}"

## telegraf
# telegraf_influxdb_urls:
#   - "http://10.42.1.42:8086"
# telegraf_influxdb_v2: true
# telegraf_influxdb_organization: ktz
# telegraf_plugins: "{{ telegraf_plugins_base }}"