---

target_os: debian #proxmox

# sicruse.powerline-fonts
powerline_users:
  - user: "{{ main_username }}"

# geerlingguy.github_users
github_users_authorized_keys_exclusive: false
github_users:
  # You can specify an object with 'name' (required) and 'groups' (optional):
  - name: "{{ main_username }}"
    groups: sudo,docker

# mqz-github-keys
github_key_users:
  - user: "{{ main_username }}"
