services:
  eplustv:
    image: tonywagner/eplustv
    environment:
      PUID: "{{ channels_dvr_puid | default('1028') }}"
      PGID: "{{ channels_dvr_pgid | default('100') }}"
    ports:
      - 8093:8000
    volumes:
      - "{{ cerebro_docker_root }}/eplustv:/app/config"
  pluto-for-channels:
    image: jonmaddox/pluto-for-channels
    container_name: pluto-for-channels
    restart: unless-stopped
    ports:
      - 8090:80
