---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: plex-test
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true # needed for Docker-in-Docker
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
    command: ""
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      roles_path: "../../../../galaxy_roles:../../../"
verifier:
  name: ansible
