---
- hosts: phoenix
  vars_files:
    - 'vars/vault.yaml'
  vars:
    setup: "{{ lookup('env', 'SETUP') | default('false') }}"
  become: true
  roles:
    # - role: geerlingguy.ntp
    # - role: singleplatform-eng.users
    # - role: geerlingguy.security
    # - role: ironicbadger.proxmox_nag_removal
    # - role: geerlingguy.docker
    # - role: grog.package
    # - role: sicruse.powerline-fonts
    # - role: mqz-github-keys
    # - role: mqz-zsh
    - role: mqz-proxmox
    # - role: mqz-phoenix


# - hosts: dazzler
#   vars_files:
#     - 'vars/vault.yaml'
#   become: yes
#   roles:
#     - role: geerlingguy.docker
#     - role: grog.package

# - hosts: cerebro
#   vars_files:
#     - 'vars/vault.yaml'
#   roles:
#     - role: ironicbadger.docker_compose_generator
#       tags: compose