---
- hosts: phoenix
  vars_files:
    - 'group_vars/secrets.yaml'
  vars:
    setup: "{{ lookup('env', 'SETUP') | default('false') }}"
  gather_facts: false
  roles:
    - role: mqz-proxmox
    - role: mqz-tailscale

- hosts: plex
  vars_files:
    - 'group_vars/secrets.yaml'
  become: true
  gather_facts: false
  roles:
    - role: mqz-plex

- hosts: caddy
  vars_files:
    - 'group_vars/secrets.yaml'
  become: true
  gather_facts: false
  roles:
    - role: mqz-caddy

- hosts: cerebro
  vars_files:
    - 'group_vars/secrets.yaml'
  gather_facts: false
  roles:
    - role: mqz-cerebro
      tags: cerebro
