---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    caddy_domain: "mqz.casa"
    cloudflare_caddy_api_token: "fake-token-for-testing"
    caddy_endpoints:
      - name: Plex
        subdomain: plex
        upstream: "http://127.0.0.1:32400"
      - name: Home Assistant
        subdomain: ha
        upstream: "http://127.0.0.1:8123"
    # systemd not available in molecule containers
    caddy_manage_service: false
  roles:
    - role: mqz-caddy
