---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: caddy-test
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: false
    cgroupns_mode: host
    capabilities:
      - NET_BIND_SERVICE
    tmpfs:
      - /run
      - /tmp
    command: ""
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
verifier:
  name: ansible
